name: SimpleBudget
targets:
  SimpleBudget:
    type: application
    platform: iOS
    deploymentTarget: "26"
    entitlements:
      path:
        SimpleBudget/SimpleBudget.entitlements
      properties:
        com.apple.developer.financekit:
          - financial-data
    info:
      path: SimpleBudget/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchScreen: {}
        ITSAppUsesNonExemptEncryption: NO
        CFBundleVersion: 1.0.3
        CFBundleShortVersionString: 1.0.3
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: dev.corybuecker.simple-budget
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      # build for iOS only
      TARGETED_DEVICE_FAMILY: 1
    sources:
      - path: SimpleBudget
