name: SimpleBudget
options:
  bundleIdPrefix: dev.corybuecker
targets:
  SimpleBudget:
    type: application
    platform: iOS
    deploymentTarget: "26"
    settings:
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      GENERATE_INFOPLIST_FILE: YES
      # build for iOS only
      TARGETED_DEVICE_FAMILY: 1
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    sources:
      - path: SimpleBudget