name: SimpleBudget
options:
  bundleIdPrefix: dev.corybuecker
settings:
  DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
targets:
  simple-budget:
    type: application
    platform: iOS
    deploymentTarget: "17.2"
    supportedDestinations: [iOS]
    settings:
      ENABLE_USER_SCRIPT_SANDBOXING: true
      TARGETED_DEVICE_FAMILY: 1 # 1: iPhone, iPod touch
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
    sources:
      - path: Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Simple Budget
        CFBundleIdentifier: dev.corybuecker.simple-budget
        CFBundleName: Budget
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0.3
        CFBundleVersion: 1.0.3
        ITSAppUsesNonExemptEncryption: false
        LSApplicationCategoryType: public.app-category.finance
        UIBackgroundModes: [remote-notification]
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
    entitlements:
      path: Sources/simple-budget.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers: [iCloud.dev.corybuecker.simple-budget]
        com.apple.developer.icloud-services: [CloudKit]

